#!/bin/sh
set -e

SOURCE=root
DEST=toshiba/zfsbackup
REMOTE=""
PREFIX=backup-toshiba

. `dirname $0`/zfs-backup-functions.sh

zfs_perform_backup -y

zfs_backup_clean_local -y
zfs_backup_clean_destination -y
zfs_backup_clean_destination_unrelated -y


